import { PERMISSIONS,ROLES,ROLE_ACCESS } from "../config/roles";

(
    function defineUserPermissions(){
        PERMISSIONS.CREATE_USER= "CREATE_USER";
        PERMISSIONS.FETCH_PROFILE= "FETCH_PROFILE";
        PERMISSIONS.UPDATE_PROFILE= "UPDATE_PROFILE";
        PERMISSIONS.DELETE_USER= "DELETE_USER";

        ROLE_ACCESS[ROLES.ADMIN]= [
            PERMISSIONS.CREATE_USER,
            PERMISSIONS.FETCH_PROFILE,
            PERMISSIONS.UPDATE_PROFILE,
            PERMISSIONS.DELETE_USER
        ];

        ROLE_ACCESS[ROLES.USER]= [
            PERMISSIONS.FETCH_PROFILE,
            PERMISSIONS.UPDATE_PROFILE
        ];
    }
)();