export const PERMISSIONS = {
  // user route permissions
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",

  // book route permissions
  CREATE_BOOK: "CREATE_BOOK",
  DELETE_BOOK: "DELETE_BOOK",
  UPDATE_BOOK: "UPDATE_BOOK",

  // book chapter route permissions
  CREATE_BOOK_CHAPTER: "CREATE_BOOK_CHAPTER",
  DELETE_BOOK_CHAPTER: "DELETE_BOOK_CHAPTER",
  UPDATE_BOOK_CHAPTER: "UPDATE_BOOK_CHAPTER",

  // conference paper route permissions
  CREATE_CONFERENCE_PAPER: "CREATE_CONFERENCE_PAPER",
  DELETE_CONFERENCE_PAPER: "DELETE_CONFERENCE_PAPER",
  UPDATE_CONFERENCE_PAPER: "UPDATE_CONFERENCE_PAPER",

  // event route permissions
  CREATE_EVENT: "CREATE_EVENT",
  DELETE_EVENT: "DELETE_EVENT",
  UPDATE_EVENT: "UPDATE_EVENT",

  // highlight route permissions
  CREATE_HIGHLIGHT: "CREATE_HIGHLIGHT",
  DELETE_HIGHLIGHT: "DELETE_HIGHLIGHT",

  // image route permissions
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  DELETE_IMAGE: "DELETE_IMAGE",

  // journal article route permissions
  CREATE_JOURNAL_PAPER: "CREATE_JOURNAL_PAPER",
  DELETE_JOURNAL_PAPER: "DELETE_JOURNAL_PAPER",
  UPDATE_JOURNAL_PAPER: "UPDATE_JOURNAL_PAPER",

  // outreach or courses route permissions
  CREATE_OUTREACH_OR_COURSES: "CREATE_OUTREACH_OR_COURSES",
  DELETE_OUTREACH_OR_COURSES: "DELETE_OUTREACH_OR_COURSES",
  UPDATE_OUTREACH_OR_COURSES: "UPDATE_OUTREACH_OR_COURSES",

  // patent route permissions
  CREATE_PATENT: "CREATE_PATENT",
  DELETE_PATENT: "DELETE_PATENT",
  UPDATE_PATENT: "UPDATE_PATENT",

  // photo gallery route permissions
  ADD_GALLERY_IMAGE: "ADD_GALLERY_IMAGE",
  DELETE_GALLERY_IMAGE: "DELETE_GALLERY_IMAGE",

  // project route permissions
  CREATE_PROJECT: "CREATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",

  // recent update route permissions
  CREATE_RECENT_UPDATE: "CREATE_RECENT_UPDATE",
  DELETE_RECENT_UPDATE: "DELETE_RECENT_UPDATE",

  // research area route permissions
  CREATE_RESEARCH_AREA: "CREATE_RESEARCH_AREA",
  DELETE_RESEARCH_AREA: "DELETE_RESEARCH_AREA",
  UPDATE_RESEARCH_AREA: "UPDATE_RESEARCH_AREA",

  // research facility route permissions
  CREATE_RESEARCH_FACILITY: "CREATE_RESEARCH_FACILITY",
  DELETE_RESEARCH_FACILITY: "DELETE_RESEARCH_FACILITY",
  UPDATE_RESEARCH_FACILITY: "UPDATE_RESEARCH_FACILITY",

} as const;
