import { PERMISSIONS } from "./permissions";
import { ROLES } from "./roles";

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
type RoleValue = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_ACCESS: Partial<Record<Permission, readonly RoleValue[]>> = {
  // user route permissions
  [PERMISSIONS.CREATE_USER]: [ROLES.ADMIN],
  [PERMISSIONS.DELETE_USER]: [ROLES.ADMIN],

  // book route permissions
  [PERMISSIONS.CREATE_BOOK]: [ROLES.ADMIN, ROLES.ALUMNI,ROLES.PHD],
  [PERMISSIONS.DELETE_BOOK]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.UPDATE_BOOK]: [ROLES.ADMIN, ROLES.ALUMNI],

  // book chapter route permissions
  [PERMISSIONS.CREATE_BOOK_CHAPTER]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.DELETE_BOOK_CHAPTER]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.UPDATE_BOOK_CHAPTER]: [ROLES.ADMIN, ROLES.ALUMNI],

  // conference paper route permissions
  [PERMISSIONS.CREATE_CONFERENCE_PAPER]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.DELETE_CONFERENCE_PAPER]: [ROLES.ADMIN],
  [PERMISSIONS.UPDATE_CONFERENCE_PAPER]: [ROLES.ADMIN, ROLES.ALUMNI],

  // event route permissions
  [PERMISSIONS.CREATE_EVENT]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.DELETE_EVENT]: [ROLES.ADMIN],
  [PERMISSIONS.UPDATE_EVENT]: [ROLES.ADMIN, ROLES.ALUMNI],

  // highlight route permissions
  [PERMISSIONS.CREATE_HIGHLIGHT]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.DELETE_HIGHLIGHT]: [ROLES.ADMIN],

  // image route permissions
  [PERMISSIONS.UPLOAD_IMAGE]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.DELETE_IMAGE]: [ROLES.ADMIN],
  // journal article route permissions
  [PERMISSIONS.CREATE_JOURNAL_PAPER]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.DELETE_JOURNAL_PAPER]: [ROLES.ADMIN],
  [PERMISSIONS.UPDATE_JOURNAL_PAPER]: [ROLES.ADMIN, ROLES.ALUMNI],
  // outreach or courses route permissions
  [PERMISSIONS.CREATE_OUTREACH_OR_COURSES]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.DELETE_OUTREACH_OR_COURSES]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.UPDATE_OUTREACH_OR_COURSES]: [ROLES.ADMIN, ROLES.ALUMNI],
  // patent route permissions
  [PERMISSIONS.CREATE_PATENT]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.DELETE_PATENT]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.UPDATE_PATENT]: [ROLES.ADMIN, ROLES.ALUMNI],

  // photo gallery route permissions
  [PERMISSIONS.ADD_GALLERY_IMAGE]: [ROLES.ADMIN],
  [PERMISSIONS.DELETE_GALLERY_IMAGE]: [ROLES.ADMIN],

  // project route permissions
  [PERMISSIONS.CREATE_PROJECT]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.DELETE_PROJECT]: [ROLES.ADMIN, ROLES.ALUMNI],
  [PERMISSIONS.UPDATE_PROJECT]: [ROLES.ADMIN, ROLES.ALUMNI],

  // recent update route permissions
  [PERMISSIONS.CREATE_RECENT_UPDATE]: [ROLES.ADMIN],
  [PERMISSIONS.DELETE_RECENT_UPDATE]: [ROLES.ADMIN],
} satisfies Partial<Record<Permission, readonly RoleValue[]>>;
